export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GO_TO_PAGE = 'GO_TO_PAGE';
